// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// /// // ...
// await Firebase.initializeApp(
//     options = DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvIDv-UK8ec1p367wEi7VAz3scx7GQ1Rc',
    appId: '1:214322470101:android:8e0345d69ec6f64dd7165c',
    messagingSenderId: '214322470101',
    projectId: 'newams-b988f',
    storageBucket: 'newams-b988f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrxNFoxEpq0ZSmW2nXIs-83xCIVACww3Y',
    appId: '1:214322470101:ios:9d1cf17e331bbb9cd7165c',
    messagingSenderId: '214322470101',
    projectId: 'newams-b988f',
    storageBucket: 'newams-b988f.appspot.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyn9UsbuEtCxOK7oemqHqBeiP-3To5kB0',
    appId: '1:214322470101:web:54be809a441abe7ad7165c',
    messagingSenderId: '214322470101',
    projectId: 'newams-b988f',
    authDomain: 'newams-b988f.firebaseapp.com',
    storageBucket: 'newams-b988f.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrxNFoxEpq0ZSmW2nXIs-83xCIVACww3Y',
    appId: '1:214322470101:ios:9d1cf17e331bbb9cd7165c',
    messagingSenderId: '214322470101',
    projectId: 'newams-b988f',
    storageBucket: 'newams-b988f.appspot.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyn9UsbuEtCxOK7oemqHqBeiP-3To5kB0',
    appId: '1:214322470101:web:7c3afeacb967e986d7165c',
    messagingSenderId: '214322470101',
    projectId: 'newams-b988f',
    authDomain: 'newams-b988f.firebaseapp.com',
    storageBucket: 'newams-b988f.appspot.com',
  );
}
